
package org.arpit.javapostsforlearning.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://webservice.javapostsforlearning.arpit.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://webservice.javapostsforlearning.arpit.org/", className = "org.arpit.javapostsforlearning.webservice.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://webservice.javapostsforlearning.arpit.org/", className = "org.arpit.javapostsforlearning.webservice.SayHelloWorldResponse")
    @Action(input = "http://webservice.javapostsforlearning.arpit.org/HelloWorld/sayHelloWorldRequest", output = "http://webservice.javapostsforlearning.arpit.org/HelloWorld/sayHelloWorldResponse")
    public String sayHelloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
